global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'proxy'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'proxy-1:8080'
          - 'proxy-2:8080'
        labels:
          app: 'proxy'

  - job_name: 'cache-node'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'cache-node-1:8081'
          - 'cache-node-2:8081'
          - 'cache-node-3:8081'
        labels:
          app: 'cache-node'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']